amazon-science/chronos-forecasting

- src/chronos/chronos.py
*Issue #, if available:* N/A
Thanks for the very clean impl of the Model, Tokenizer, and Pipeline. 
I was curios about it and found a minor improvement in the API - what do you think about it? Feel free to close. Change is untested.
> Update chronos.py - model.device

- pyproject.toml
> Bump package version to 1.1

- .github/workflows/ci.yml
- pyproject.toml
- src/chronos/chronos.py
- test/test_chronos.py
*Description of changes:* Fix some type checking issues, add mypy to github workflow, apply black
> Fix types, add mypy to workflow

- .github/workflows/ci.yml
*Description of changes:* Speed up GH workflow by installing CPU-only version of torch
> Speed up workflow

- scripts/kernel-synth.py
- scripts/training/train.py
> Add missing headers

- pyproject.toml
*Issue #, if available:* #76
*Description of changes:* transformers 4.41 broke something for us, we need to look into it deeper
> Cap transformers <4.41

- scripts/training/train.py
*Description of changes:* This PR updates the training script to also save the training details in the final checkpoint.
> Save training job info

- .github/workflows/ci.yml
*Description of changes:* Run CI at 8 AM UTC every day.
> Update ci.yml with schedule

- README.md
> Add FAQ badge to README

- scripts/training/train.py
*Description of changes:* Removes print statements that got left inside from a debugging session.
> Remove print statements from `train.py`

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
*Description of changes:* adding templates for GitHub issues.
> Add issue templates

- README.md
*Description of changes:* This PR updates README.md with dataset and evaluation details
> Update README.md with dataset and evaluation details

- scripts/evaluation/evaluate.py
*Description of changes:* Adds generation params to command line options for the evaluation script. 
> Add generation params to eval script

- .github/workflows/ci.yml
- .github/workflows/publish-to-pypi.yml
- README.md
- pyproject.toml
*Description of changes:* This PR updates project information and workflows to allow for PyPi release.
> Update project information and workflows

- README.md
*Description of changes:* MPS mostly causes issues for users, so let's remove the reference to MPS from the README. Plus, Chronos-Bolt models currently fail on MPS. 
> Remove reference to MPS

- .github/workflows/ci.yml
> Run type checks on Python 3.11 only

- README.md
*Description of changes:* `predict` returns different things based on model type. This fixes the example to use `predict_quantiles` which will give correct quantiles.
> Fix README example to use `predict_quantiles`

- pyproject.toml
*Description of changes:* Title.
> Bump version to 1.4.0

- pyproject.toml
> Bump version number to 1.4.1

- scripts/README.md
*Issue #, if available:* Fixes #235 
> Fix training install instructions

- .github/ISSUE_TEMPLATE/config.yml
*Description of changes:* remove blank issue button, update description of link to discussions 
> Update issue templates 

- pyproject.toml
> Bump package version to 1.5.0

- pyproject.toml
*Issue #, if available:* addresses https://github.com/amazon-science/chronos-forecasting/security/dependabot/1
> Bump transformers to >=4.48

- pyproject.toml
Just increased the max version allowed. Tests pass.
> Bump `accelerate>=0.32,<2`

- pyproject.toml
> Bump version to 1.5.2
